#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MEMORY_SIZE 4096 //4KiB
#define DISPLAY_HEIGHT 32
#define DISPLAY_WIDTH 64

#define TIMERS_FREQUENCY 60 //Hz
#define TIMERS_DELAY 1000/TIMERS_FREQUENCY //ms

#define CPU_FREQUENCY 700 //Hz
#define CPU_DELAY 1000/CPU_FREQUENCY //ms

#define DISPLAY_FREQUENCY 60 //Hz
#define DISPLAY_DELAY 1000/DISPLAY_FREQUENCY //ms

#endif